# Generated by Django 5.0.6 on 2024-07-08 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0002_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='car',
            name='quantity',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
