# Generated by Django 5.0.6 on 2024-07-08 08:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0005_order_cars'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='cars',
        ),
        migrations.AddField(
            model_name='order',
            name='cars',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='car.car'),
        ),
    ]
